apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubest.fullname" . }}
  labels:
    {{- include "kubest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "kubest.selectorLabels" . | nindent 4 }}
